using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Class for holding the names to genrate planet names for Points

public static class PlanetNames 
{
    // Planets names are as such: [Adjective] [Noun] - [Number]

    public static string GeneratePlanetName() {
        string name = "";
        name += GenerateAdjective() + " " + GenerateNoun() + " - " + Random.Range(0, 1000000).ToString();
        return name;
    }

    private static string GenerateAdjective() {
        return ((Adjective)Random.Range(0, System.Enum.GetValues(typeof(Adjective)).Length)).ToString();
    }

    private static string GenerateNoun() {
        return ((Noun)Random.Range(0, System.Enum.GetValues(typeof(Noun)).Length)).ToString();
    }

}

// Enums for [Adjective] and [Noun]
public enum Adjective {
    Red,
    Blue,
    Green,
    Yellow,
    Purple,
    Orange,
    White,
    Black,
    Grey,
    Pink,
    Brown,
    Gold,
    Silver,
    Copper,
    Platinum,
    Titanium,
    Iron,
    Steel,
    Crystal,
    Diamond,
    Emerald,
    Ruby,
    Sapphire,
    Topaz,
    Quartz,
    Granite,
    Marble,
    Obsidian,
    Lava,
    Ice,
    Snow,
    Frost,
    Fire,
    Flame,
    Smoke,
    Ash,
    Dust,
    Sand,
    Desert,
    Oasis,
    Jungle,
    Forest,
    Wood,
    Tree,
    Leaf,
    Flower,
    Rose,
    Daisy,
    Lily,
    Orchid,
    Tulip,
    Sunflower,
    Dandelion,
    Violet,
    Iris,
    Poppy,
    Carnation,
    Hyacinth,
    Aster,
    Peony,
    Magnolia,
    Jasmine,
    Lavender,
    Lilac,
    Thistle,
    Clover,
    Shamrock,
    Ivy,
    Fern,
    Moss,
    Seaweed,
    Coral,
    Algae,
    Kelp,
    Seashell,
    Pearl,
    Starfish,
    Jellyfish,
    Crab,
    Lobster,
    Shrimp,
    Prawn,
    Squid,
    Octopus,
    Cuttlefish,
    Nautilus,
    Snail,
    Slug,
    Worm,
    Beetle,
    Ant,
    Bee,
    Wasp,
    Hornet,
    Fly,
    Mosquito,
    Dragonfly,
    Damselfly,
    Butterfly,
    Moth,
    Caterpillar,
    Larva,
    Pupa,
    Cocoon,
    Chrysalis,
    Spider,
    Scorpion,
    Tarantula,
    Centipede,
    Millipede,
    Grasshopper,
    Cricket,
    Locust,
    Katydid,
    Cicada,
    Ladybug,
    Aphid,
    Mantis,
    Stickbug,
    Leafbug,
    Lanternbug,
    Firefly,
    Glowworm,
    Earthworm,
    Leech,
    Clam,
    Oyster,
    Mussel,
    Scallop,
    Conch,
    Whelk,
    Cowrie
}

public enum Noun {
    Planet,
    Star,
    Moon,
    Sun,
    Galaxy,
    Nebula,
    Cluster,
    System,
    Universe,
    Cosmos,
    Space,
    Void,
    BlackHole,
    Wormhole,
    Quasar,
    Pulsar,
    Supernova,
    Comet,
    Asteroid,
    Meteor,
    Meteorite,
    Meteoroid,
    Dwarf,
    Giant,
    SuperGiant,
    HyperGiant
}